### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ricky4026** [ricky4026/issue#1]
2018.09.03
問題1:  MOXA的COM只要插不同USB孔就會得到不同的COM,能否強制鎖定?
問題2:  新程式狀態列不會跑,但可與MOXA溝通
問題3:  5秒內讀不到藥品程式會卡住
問題4:  舊版VP可連MOXA也可連主機板,但手動包裝時不會數藥(只會拖紙與壓合)
2018.09.18
問題1: 只設定1號藥盒1包1顆,包出來會有4包裡面都1顆
問題2: 漏斗擋板裝置需要先新增程式上去

**Comment by ricky4026** [comment]
2018.09.19
新底層安裝完後,無法手動包裝,完全沒反應
VP是使用09.19的PressFitVP-A1-Test1版本
MDU可掉藥

**Comment by proteljack** [comment]
2018.09.19  回覆
已解決，上傳Github造成的問題。
